kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-home
  labels:
    type: local
  namespace: kubernetes-plugin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/jenkins_home/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-home-jenkins-0
  namespace: kubernetes-plugin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
