---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-l5d-config
data:
  config.yaml: |-
    admin:
      ip: 0.0.0.0
      port: 9990

    namers:
    - kind: io.l5d.k8s

    routers:
    - protocol: http
      identifier:
        kind: io.l5d.ingress
      servers:
        - port: 80
          ip: 0.0.0.0
          clearContext: true
      dtab: /svc => /#/io.l5d.k8s
      client:
        kind: io.l5d.global
        loadBalancer:
          kind: ewma
        requeueBudget: 
          percentCanRetry: 0.2
        failureAccrual:
          kind: io.l5d.consecutiveFailures
          failures: 3
          backoff:
            kind: jittered
            minMs: 10000
            maxMs: 20000
      service:
        totalTimeoutMs: 60000
        responseClassifier:
          kind: io.l5d.http.retryableRead5XX
        retries:
          budget:
            minRetriesPerSec: 5
            percentCanRetry: 0.5
            ttlSecs: 5
          backoff:
            kind: jittered
            minMs: 10
            maxMs: 10000

    usage:
      orgId: {{ .Release.Name }}-linkerd-examples-ingress
    
    telemetry:
      - kind: io.l5d.prometheus
      - kind: io.l5d.recentRequests
        sampleRate: 0.25