---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-l5d
spec:
  selector:
    app: {{ .Release.Name }}-l5d
  type: NodePort
  ports:
  - name: http
    port: 80
  - name: admin
    port: 9990
