apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - /opt/helmet
          - -stderrthreshold=INFO
          - -host=0.0.0.0
          - -port={{ .Values.service.internalPort }}
          - -url=http://{{ template "fullname" . }}:{{ .Values.service.internalPort }}/charts/
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /charts/index.yaml
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /charts/index.yaml
            port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}

